services:
    db:
        image: postgres:16-alpine
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
        ports:
            - '5432:5432'
        volumes:
            - postgres13:/var/lib/postgresql/data
    redis:
        image: redis:7.0.15-alpine
        ports:
        - '6379:6379'
        volumes:
        - redis_data:/data  
    web:
      build: .
      entrypoint: ./ops/web_entrypoint.sh
      volumes:
        - .:/rails
        - bundle_cache_web:/usr/local/bundle
      ports:
        - "3000:3000"
      depends_on:
        - db
        - redis
      environment:
        - RAILS_ENV=development
        - DATABASE_URL=postgresql://postgres:password@db:5432/store
        - REDIS_URL=redis://redis:6379/0
        - RAILS_LOG_TO_STDOUT=true

    jobs:
      build: .
      entrypoint: ./ops/jobs_entrypoint.sh
      volumes:
        - .:/rails
        - bundle_cache_jobs:/usr/local/bundle
      depends_on:
        - db
        - redis
      environment:
        - RAILS_ENV=development
        - DATABASE_URL=postgresql://postgres:password@db:5432/store
        - REDIS_URL=redis://redis:6379/0
    test:
        build: .
        entrypoint: ./ops/test_entrypoint.sh
        volumes:
          - .:/rails
          - bundle_cache_test:/usr/local/bundle
        depends_on:
          - db
          - redis
        environment:
          - RAILS_ENV=test
          - DATABASE_URL=postgresql://postgres:password@db:5432/store_test
          - REDIS_URL=redis://redis:6379/0
          - COVERAGE=1
    swagger:
      image: swaggerapi/swagger-ui:latest
      container_name: swagger-ui
      ports:
        - "8080:8080"
      environment:
        SWAGGER_JSON: /spec/openapi.yml
      volumes:
        - ./api/openapi.yml:/spec/openapi.yml:ro
      restart: unless-stopped
      depends_on:
        - db
        - redis
        - web
volumes:
    postgres13:
    redis_data:
    bundle_cache_test:
    bundle_cache_web:
    bundle_cache_jobs:
