version: '3'

services:
    db:
        image: postgres:16-alpine
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
        ports:
            - '5432:5432'
        volumes:
            - postgres13:/var/lib/postgresql/data
    redis:
        image: redis:7.0.15-alpine
        ports:
        - '6379:6379'
        volumes:
        - redis_data:/data  
    web:
      build: .
      entrypoint: ./ops/web_entrypoint.sh
      volumes:
        - .:/rails
        - bundle_cache_web:/usr/local/bundle
      ports:
        - "3000:3000"
      depends_on:
        - db
        - redis
      environment:
        - DATABASE_URL=postgresql://postgres:password@db:5432/store
        - RAILS_ENV=development
        - RAILS_LOG_TO_STDOUT=true
    test:
        build: .
        entrypoint: ./ops/test_entrypoint.sh
        volumes:
          - .:/rails
          - bundle_cache_test:/usr/local/bundle
        depends_on:
          - db
          - redis
        environment:
          - DATABASE_URL=postgresql://postgres:password@db:5432/store_test
          - REDIS_URL=redis://redis:6379/0
          - COVERAGE=1
volumes:
    postgres13:
    redis_data:
    bundle_cache_test:
    bundle_cache_web:
